environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - "set PATH=%PYTHON%\\Scripts;%PATH%"
  - "%PYTHON%\\python.exe -m pip install -e ."

build: off

test_script:
    - "%PYTHON%\\python.exe -m pytest -v"
    - "pycon verify"
    - "tutorial version"
    - "tutorial init"
    - "tutorial lesson"
    - "tutorial solve --yes"
    - "tutorial check"

#after_test:
    # None

#artifacts:
    # None

#on_success:
    # None
